const wordData = [
  { word: "前年", pinyin: "qiannian", meaning: "the year before last; two years ago" },
  { word: "包", pinyin: "bao", meaning: "bag; package" },
  { word: "當地", pinyin: "dangdi", meaning: "local; from the area" },
  { word: "名產", pinyin: "mingchan", meaning: "local specialty; famous local product" },
  { word: "明信片", pinyin: "mingxinpian", meaning: "postcard" },
  { word: "訂", pinyin: "ding", meaning: "to reserve; to book; to order" },
  { word: "免費", pinyin: "mianfei", meaning: "free of charge" },
  { word: "無線網路", pinyin: "wuxianwangluo", meaning: "Wi-Fi; wireless Internet" },
  { word: "美麗", pinyin: "meili", meaning: "beautiful" },
  { word: "美", pinyin: "mei", meaning: "pretty; beautiful" },
  { word: "毛", pinyin: "mao", meaning: "a dime; ten cents" },
  { word: "讓", pinyin: "rang", meaning: "to let; to allow; to make" },
  { word: "正在", pinyin: "zhengzai", meaning: "in the middle of (doing)" },
  { word: "公路", pinyin: "gonglu", meaning: "highway; main road" },
  { word: "石頭", pinyin: "shitou", meaning: "stone; rock" },
  { word: "掉", pinyin: "diao", meaning: "to drop; to fall off" },
  { word: "下來", pinyin: "xialai", meaning: "to come down" },
  { word: "一下子／一下子兒", pinyin: "yixiazi / yixiazir", meaning: "suddenly; quickly" },
  { word: "光", pinyin: "guang", meaning: "used up; nothing left" },
  { word: "鐵路", pinyin: "tielu", meaning: "railway" },
  { word: "鐵", pinyin: "tie", meaning: "iron; metal" },
  { word: "網頁", pinyin: "wangye", meaning: "web page" },
  { word: "訂位", pinyin: "dingwei", meaning: "to reserve a seat" },
  { word: "底", pinyin: "di", meaning: "bottom; end (of a period)" },
  { word: "出發", pinyin: "chufa", meaning: "to set out; to depart" },
  { word: "國家公園", pinyin: "guojiagongyuan", meaning: "national park" },
  { word: "爬", pinyin: "pa", meaning: "to climb; to hike" },
  { word: "座位", pinyin: "zuowei", meaning: "seat" },
  { word: "位子", pinyin: "weizi", meaning: "seat; place (informal)" },
  { word: "記", pinyin: "ji", meaning: "to write down; to remember" },
  { word: "日期", pinyin: "riqi", meaning: "date" }
];